/*
Given a string s consisting only of letters 'a' and 'b'. In a single step you can remove one palindromic subsequence from s.

Return the minimum number of steps to make the given string empty.

A string is a subsequence of a given string, if it is generated by deleting some characters of a given string without changing its order.

A string is called palindrome if is one that reads the same backward as well as forward.

Link - https://leetcode.com/explore/challenge/card/march-leetcoding-challenge-2021/589/week-2-march-8th-march-14th/3665/
*/

class Solution {
    public int removePalindromeSub(String s) {
        if(s.length()==0)
            return 0;
        else if(palindrome(s))
            return 1;
        else
            return 2;
    }
    public boolean palindrome(String s) {
        int i = 0, j = s.length() - 1;
        while(i<j) {
            if(s.charAt(i)==s.charAt(j)) {
                i++;
                j--;
            } else
                return false;
        }
        return true;
    }
}
